typography_spectrum: 0.004730255575850606
color:
  brandStrength: 0.4027740238234401
  lightness: 0.962365505984053
  saturation: 0.39971250062808394
  rhythmicContrast: 0.9275107081048191
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
layout_spectrum: 0.4246262570377439
author:
  name: Mattimore Cronin
  email: mattimorecronin@gmail.com
  url: 'http://artificialuprising.com'
name: Artificial Uprising
title: Countdown to the Artificial Superintelligence Revolution
description: Be the first to know when it all goes down
